nasa/trick

- bin/trick-CP
make system.
***     ***
**   ** **   **
*       *       *
*   MAKE_out    *
*             *
**         **
**     **
** **
-------------------        *        --------------------
../                     \..         ../                     \..
/                           \       /                           \
|.,       __   _..._          \     /        ....     ___         |
/  \     /  `-'     `-------...    ..--`````'    `--'    \.    ./` \
|   \--_-               /    o ``X'  o    \                '--/    |
|         ( ( ( ( (    /    \   /``\   /   \  ) ) ) ) )            |
|   /---\                   ./|`    |`\.                  ..-..    |
|  /     \-..-........-```/`./       \..`--.........-.  ./     `-./
`'\                      /             \.            ``       /-- …
> Added optional var=value support for trick-CP as passthroughs to the

- libexec/trick/make_makefile_src
- share/trick/makefiles/Makefile.common
- share/trick/makefiles/Makefile.sim
I'm applying what I've learned in EG2: proper git workflow!
Refs #360
> Remove double include of S_overrides.mk

- trick_source/codegen/Interface_Code_Gen/FieldDescription.cpp
- trick_source/codegen/Interface_Code_Gen/PrintAttributes.cpp
- trick_source/data_products/Log/Csv.cpp
- trick_source/data_products/Log/MatLab.cpp
- trick_source/data_products/Log/MatLab4.cpp
- trick_source/data_products/Log/TrickBinary.cpp
- trick_source/data_products/Log/TrickHDF5.cpp
- trick_source/data_products/Log/log.cpp
- trick_source/sim_services/DataTypes/src/ArrayDataType.cpp
- trick_source/sim_services/DataTypes/src/CompositeDataType.cpp
- trick_source/sim_services/DataTypes/src/MemMgr.cpp
- trick_source/sim_services/MemoryManager/MemoryManager_alloc_depends.cpp
- trick_source/sim_services/MemoryManager/MemoryManager_get_stl_dependencies.cpp
- trick_source/sim_services/MemoryManager/MemoryManager_restore_stls.cpp
> Use std::cerr instead of std::cout for error messages

- include/trick/trick_math.h
Its easier to read this way. Upgrade readability of the code.
> Align both M_PI and M_PI_2 values.

- bin/pm/parse_s_define.pm
- makefiles/Makefile.common
- trick_source/codegen/Interface_Code_Gen/CommentSaver.cpp
- trick_source/codegen/Interface_Code_Gen/CommentSaver.hh
- trick_source/codegen/Interface_Code_Gen/FieldVisitor.cpp
- trick_source/er7_utils/integration/beeman/src/beeman_integrator_constructor.cc
- trick_source/er7_utils/integration/core/include/generalized_position_derivative.hh
- trick_source/er7_utils/integration/core/include/integration_controls.hh
- trick_source/er7_utils/integration/rkn4/include/rkn4_second_order_ode_integrator.hh
- trick_source/er7_utils/interface/include/alloc.hh
- trick_source/er7_utils/interface/include/type_traits.hh
- trick_source/er7_utils/math/include/n_choose_m.hh
- trick_source/er7_utils/math/include/ratio128.hh
- trick_source/sim_services/CheckPointAgent/include/ClassicCheckPointAgent.hh
- trick_source/sim_services/Executive/include/sim_mode.h
- trick_source/sim_services/Integrator/include/IntegLoopManager.hh
- trick_source/sim_services/Integrator/include/IntegLoopScheduler.hh
- trick_source/sim_services/MemoryManager/include/MemoryManager.hh
- trick_source/sim_services/MemoryManager/include/parameter_types.h
- trick_source/sim_services/Message/include/message_type.h
- trick_source/sim_services/ScheduledJobQueue/include/ScheduledJobQueue.hh
- trick_source/sim_services/Scheduler/include/Scheduler.hh
- trick_source/sim_services/SimObject/include/JobData.hh
- trick_source/sim_services/SimObject/include/SimObject.hh
Updated pull request, more or less the same as #417, but against 15 as opposed to master.
This pull request is against issue #416, using the 15 branch as a base. I based my work on the 15.2.3 tag. (Sorry Alex; that's what we're using as a baseline.)
> Hammen doxygen comments

- include/trick/MonteCarlo.hh
- trick_source/sim_services/MonteCarlo/MonteCarlo.cpp
- trick_source/sim_services/MonteCarlo/MonteCarlo_funcs.cpp
This is in reference to issue #398.
> Removed default_port_flag and socket_init. 

- include/trick/MonteCarlo.hh
- trick_source/sim_services/MonteCarlo/MonteCarlo.cpp
- trick_source/sim_services/MonteCarlo/MonteCarlo_funcs.cpp
Reverts nasa/trick#442
Jenkins is not happy. :(
> Revert "Removed default_port_flag and socket_init. "

- trick_sims/Cannon/models/cannon/optim/src/monte_shutdown.c
It is unknown if this character array was the initial cause of the #356, but it needed to be fixed regardless.
> Sim monte freeze fix.

- bin/trick-units
This is the squashed version of the previous pull request #460.
This pull request is in reference to issue #455.
> Added "trick-units" perl script.

- libexec/trick/pm/get_lib_deps.pm
This pull request is in reference to issue #329.
> Replaced smartmatch operator with string equality operation.

- test/makefile
This pull request references issue #463.
> Added more test directories to "make clean".

- include/trick/MonteVar.hh
- include/trick/MonteVarCalculated.hh
- include/trick/MonteVarFile.hh
- include/trick/MonteVarFixed.hh
- include/trick/MonteVarRandom.hh
- include/trick/StlRandomGeneratorSub.hh
- trick_source/sim_services/MonteCarlo/MonteCarlo_c_intf.cpp
- trick_source/sim_services/MonteCarlo/MonteCarlo_funcs.cpp
- trick_source/sim_services/MonteCarlo/MonteCarlo_master_file_io.cpp
- trick_source/sim_services/MonteCarlo/MonteVarCalculated.cpp
- trick_source/sim_services/MonteCarlo/MonteVarFile.cpp
- trick_source/sim_services/MonteCarlo/MonteVarFixed.cpp
- trick_source/sim_services/MonteCarlo/MonteVarRandom.cpp
This pull request in response to issue #485.
> Added additional variable information to the Monte_Runs data file.

- trick_source/sim_services/MonteCarlo/MonteVarFile.cpp
This pull request is in reference to issue #519.
> Fixed the MC 'file failed to open' error.

- include/trick/tc.h
- test/SIM_rti/ClassOfEverything.hh
- test/SIM_test_dp/models/dp/include/dp.h
- trick_source/data_products/DPX/DPC/DPC_curve.hh
- trick_source/data_products/DPX/DPV/DPV_view.hh
- trick_source/data_products/DPX/test/unit_test/DS_test.cpp
- trick_source/data_products/DPX/test/unit_test/test_view.cpp
- trick_source/data_products/DPX/test/unit_test/test_view.hh
- trick_source/sim_services/Clock/test/BC635Clock_test.cpp
- trick_source/sim_services/Clock/test/GetTimeOfDayClock_test.cpp
- trick_source/sim_services/Clock/test/TPROCTEClock_test.cpp
- trick_source/sim_services/DataRecord/DRHDF5.cpp
- trick_source/sim_services/Executive/Executive_isThreadReadyToRun.cpp
- trick_source/sim_services/Executive/test/Executive_test.cpp
- trick_source/sim_services/Integrator/test/Integrator_unittest.cc
- trick_source/sim_services/JSONVariableServer/JSONVariableServer.cpp
- trick_source/sim_services/MemoryManager/test/MM_user_defined_types.hh
- trick_source/sim_services/Message/MessageTCDevice.cpp
- trick_source/sim_services/Timer/test/ITimer_test.cpp
- trick_source/sim_services/UdUnits/UdUnits.cpp
- trick_source/sim_services/VariableServer/VariableServerListenThread.cpp
- trick_source/trick_utils/comm/test/TCConnectTest.cpp
This pull request has taken care of all unit test warnings as well as a few compilation warnings.
The issue referenced by this pull request is: #504.
> Some unit test warnings addressed.

- trick_source/trick_utils/math/src/deuler_123_quat.c
- trick_source/trick_utils/math/src/deuler_132_quat.c
- trick_source/trick_utils/math/src/deuler_213_quat.c
- trick_source/trick_utils/math/src/deuler_231_quat.c
- trick_source/trick_utils/math/src/deuler_312_quat.c
- trick_source/trick_utils/math/src/deuler_321_quat.c
- trick_source/trick_utils/math/src/dm_invert.c
- trick_source/trick_utils/math/src/dm_invert_symm.c
- trick_source/trick_utils/math/src/tm_print_error.c
Just fixing a typo in local variable name in trick math.
> Fixing typos in trick_math

- trick_source/java/src/trick/dataproducts/trickqp/utils/TrickQPActionController.java
> Double clicking array variable in Trick QP adds it correctly once again.

- include/trick/DRBinary.hh
- include/trick/DataRecordDispatcher.hh
- include/trick/DataRecordGroup.hh
- include/trick/data_record_proto.h
- trick_source/java/src/trick/dre/DreApplication.java
- trick_source/sim_services/DataRecord/DRAscii.cpp
- trick_source/sim_services/DataRecord/DRBinary.cpp
- trick_source/sim_services/DataRecord/DataRecordDispatcher.cpp
- trick_source/sim_services/DataRecord/DataRecordGroup.cpp
- trick_source/sim_services/DataRecord/data_record_utilities.cpp
#585 
Create DataRecordGroup method for setting max log file size (ascii and binary only).
Create corresponding DataRecordDispatcher method and C interface method.
Add support to Dr. Dre for max file size.
Refactor Dr. Dre code.
Size is specified in bytes. Default is 1 GiB. For unlimited, specify 0 in *.dr file or in input file.
> Limit log file size

- libexec/trick/pm/launch_java.pm
I edited a perl script. I only did it for the betterment of mankind.
> #604 #490 add java.se.ee to application at runtime.

- trick_source/sim_services/Executive/Executive_loop_multi_thread.cpp
Thank you Steven Scheinholtz for this fix! @scheiny
> #588 top_of_frame and _end_of_frame fix for scheduled threads

- libexec/trick/make_makefile_src
- test/SIM_makefile_overrides/.gitignore
- test/SIM_makefile_overrides/models/Baz.c++
- test/SIM_makefile_overrides/models/Baz.hh
- test/SIM_makefile_overrides/models/Foo.cpp
- test/SIM_makefile_overrides/models/Foo.hh
- test/SIM_makefile_overrides/models/include/Bar.hh
- test/SIM_makefile_overrides/models/makefile_overrides
- test/SIM_makefile_overrides/models/potato/include/Flapjack.hh
- test/SIM_makefile_overrides/models/potato/makefile_overrides
- test/SIM_makefile_overrides/models/potato/src/Flapjack.cpp
- test/SIM_makefile_overrides/models/src/Bar.cxx
- test/SIM_makefile_overrides/models/src/makefile_overrides
- test/SIM_makefile_overrides/models/stupid/Stupid.cpp
- test/SIM_makefile_overrides/models/stupid/Stupid.hh
- test/SIM_makefile_overrides/models/stupid/include/ReallyStupid.hh
- test/SIM_makefile_overrides/models/stupid/src/ReallyStupid.cpp
- test/makefile
> Fix "objects:" in makefile_overrides

- libexec/trick/make_makefile_src
> Fix make_makefile_src on CentOS 6

- trick_source/data_products/Apps/trkConvert/DocWindow.cpp
- trick_source/data_products/Apps/trkConvert/DocWindow.h
- trick_source/data_products/Apps/trkConvert/TRK_DataLog.cpp
- trick_source/data_products/Apps/trkConvert/TRK_DataLog.hh
- trick_source/data_products/Apps/trkConvert/main.cpp
Just organizing some code to make it clearer.
> Refactoring in trkConvert

- libexec/trick/java/lib/Makefile
- trick_source/java/src/trick/dataproducts/plot/JXPlotApplication.java
- trick_source/java/src/trick/dataproducts/plot/utils/TrickChartFrame.java
There being some question about whether iText is open source, we're iText with PDFBox which definitely is open source.
> Replace iText Java PDF library with PDFBox.

- include/trick/checkpoint_map.hh
- include/trick/checkpoint_pair.hh
- include/trick/checkpoint_queue.hh
- include/trick/checkpoint_sequence_stl.hh
- include/trick/checkpoint_stack.hh
> #674 handle bad typeid

- share/trick/makefiles/trickify.mk
> SWIG all of S_library_swig during Trickification

- share/trick/makefiles/trickify.mk
> Add missing dependency to Trickification makefile

- bin/trick-CP
I created a new trick-cp help message from the man page.
> #677 Add trick-cp --help message

- include/trick/files_to_ICG.hh
- share/trick/trick_ver.txt
- trick_source/trick_swig/sim_services.i
> Add ExecutiveException.hh to sim_services.i

- include/trick/MonteVarRandom.hh
- trick_source/sim_services/MonteCarlo/MonteVarRandom.cpp
> Add accessor for MonteVarRandom::randist

- include/trick/files_to_ICG.hh
- trick_source/trick_swig/sim_services.i
units_conv.h was also missing from sim_services.i
Closes #718
> Add Unit.hh to files_to_ICG.hh & sim_services.i

- bin/trick-CP
- libexec/trick/make_makefile_src
- libexec/trick/make_makefile_swig
- share/trick/makefiles/Makefile.common
- trick_source/codegen/Interface_Code_Gen/PrintAttributes.hh
VERBOSE is a synonym for TRICK_VERBOSE_BUILD
> Verbose synonym

- libexec/trick/make_makefile_swig
> Immediately add file to md5s after check

- trick_source/sim_services/CheckPointAgent/ClassicCheckPointerAgent.cpp
- trick_source/sim_services/DataTypes/src/ClassicChkPtAgent.cpp
- trick_source/sim_services/DataTypes/src/CompositeDataType.cpp
- trick_source/sim_services/DataTypes/src/EnumDataType.cpp
- trick_source/sim_services/JSONVariableServer/JSONVariableServer.cpp
- trick_source/sim_services/MemoryManager/MemoryManager_JSON_Intf.cpp
- trick_source/sim_services/Message/MessageTCDevice.cpp
- trick_source/sim_services/MonteCarlo/MonteCarlo_dryrun.cpp
- trick_source/sim_services/ThreadBase/ThreadBase.cpp
- trick_source/sim_services/VariableServer/VariableServer.cpp
- trick_source/sim_services/VariableServer/VariableServerThread.cpp
This addresses issue #766 in places other than SIE.
> Change std::endl to linefeed as appropriate. 

- autoconf/configure.ac
- configure
- libexec/trick/make_makefile_swig
- share/trick/makefiles/trickify.mk
Require SWIG >= 2.0
Closes #505
> Autogenerate SWIG dependencies

- bin/trick-CP
> Remove - from most -includes in SIM_*/makefile

- bin/trick-CP
- libexec/trick/make_makefile_src
> Remove redundant prerequisite for "all" target

- libexec/trick/make_makefile_src
> Remove make target "sie"

- libexec/trick/make_makefile_swig
> Clean up inconsistencies in make_makefile_swig

- libexec/trick/make_makefile_swig
> Redo accidentally undone changes

- libexec/trick/make_makefile_swig
- libexec/trick/pm/get_paths.pm
> Remove SWIG_*_CUSTOM_OUTDIR

- libexec/trick/convert_swig
- libexec/trick/make_makefile_swig
- libexec/trick/pm/default_data.pm
- libexec/trick/pm/get_lib_deps.pm
- libexec/trick/pm/get_paths.pm
- libexec/trick/pm/parse_s_define.pm
> Use TRICK_CXXFLAGS for include paths & defines

- libexec/trick/make_makefile_swig
> Fix TRICK_VER in make_makefile_swig

- Makefile
- test/makefile
- trick_source/er7_utils/.gitignore
- trick_source/er7_utils/common.mk
- trick_source/er7_utils/integration/abm4/Makefile
- trick_source/er7_utils/integration/beeman/Makefile
- trick_source/er7_utils/integration/core/Makefile
- trick_source/er7_utils/integration/euler/Makefile
- trick_source/er7_utils/integration/mm4/Makefile
- trick_source/er7_utils/integration/nl2/Makefile
- trick_source/er7_utils/integration/position_verlet/Makefile
- trick_source/er7_utils/integration/rk2_heun/Makefile
- trick_source/er7_utils/integration/rk2_midpoint/Makefile
- trick_source/er7_utils/integration/rk4/Makefile
- trick_source/er7_utils/integration/rkf45/Makefile
- trick_source/er7_utils/integration/rkf78/Makefile
- trick_source/er7_utils/integration/rkg4/Makefile
- trick_source/er7_utils/integration/rkn4/Makefile
- trick_source/er7_utils/integration/symplectic_euler/Makefile
- trick_source/er7_utils/integration/velocity_verlet/Makefile
- trick_source/er7_utils/interface/Makefile
- trick_source/er7_utils/math/Makefile
- trick_source/er7_utils/trick/integration/Makefile
> Give er7_utils proper Makefiles

- include/trick/Executive.hh
- include/trick/MonteCarlo.hh
- trick_source/sim_services/Executive/Executive.cpp
- trick_source/sim_services/MonteCarlo/MonteCarlo_funcs.cpp
- trick_source/sim_services/MonteCarlo/MonteCarlo_master_shutdown.cpp
- trick_source/sim_services/MonteCarlo/MonteCarlo_receive_results.cpp
> Note the process exit status of Monte Carlo runs

- include/trick/swig/swig_int_typemap.i
> Add signed types to swig_int_typemap.i

- include/trick/checkpoint_map.hh
- include/trick/checkpoint_queue.hh
- include/trick/checkpoint_sequence_stl.hh
- include/trick/checkpoint_stack.hh
- trick_source/codegen/Interface_Code_Gen/ClassVisitor.cpp
> remove deprecated std::ptr_fun and std::not1 closes #864

- libexec/trick/convert_swig
- libexec/trick/pm/get_lib_deps.pm
- libexec/trick/pm/get_paths.pm
> Skip paths in TRICK_EXT_LIB_DIRS in get_lib_deps

- Makefile
- bin/trick-CP
- trick_source/codegen/Interface_Code_Gen/FindTrickICG.cpp
- trick_source/codegen/Interface_Code_Gen/main.cpp
- trick_source/sim_services/MemoryManager/test/Makefile
Some small changes/bug fixes to support LLVM 9
> Llvm 9 support

- libexec/trick/pm/verbose_build.pm
How I hate you, Perl.
Fixes #873
> Fix VERBOSE=1 in verbose_build.pm

- trick_source/sim_services/DataTypes/src/EnumDataType.cpp
- trick_source/sim_services/MemoryManager/MemoryManager_ref_assignment.cpp
I duplicated the existing code for other sizes and tested it, but I don't have much insight into what that code is really doing, so double-check me please.
Fixes #876
> Add support for char-sized enums

- Makefile
- trick_source/web/HttpServer/makefile
also get (using curl) a versioned mongoose as opposed to master.
> Fix a race condition between ICG and mongoose install

- trick_source/web/HttpServer/src/VariableServerVariable.cpp
- trick_source/web/mockup/.gitignore
- trick_source/web/mockup/.prettierrc
- trick_source/web/mockup/src/AppStyles.js
- trick_source/web/mockup/src/Client.js
- trick_source/web/mockup/src/withRoot.js
Fast-forwarding my app to the latest version to make it available and minimize integration problems later on. The app still requires several features to be implemented such as a Search feature for TV.
Currently, the process for using the app is as follows:
1. Install Node.js. https://nodejs.org/en/ or alternatively find a repository such as NodeSource
2. ```cd trick/trick_source/web/mockup```
3. ```npm i``` 
4. ```npm run build```
5. Copy the contents of the build directory to your www directory for your sim
> Update react-based Trick Dashboard

- libexec/trick/convert_swig
- test/SIM_default_member_initializer/S_define
- test/SIM_default_member_initializer/S_overrides.mk
- test/SIM_default_member_initializer/models/Foo.hh
- test/makefile
> Support default member initializers for templates

- autoconf/configure.ac
- configure
> --with-python

- trick_source/codegen/Interface_Code_Gen/ConstructValues.cpp
> Replace : in ConstructValues::mangle_template_param

- trick_source/codegen/Interface_Code_Gen/CommentSaver.cpp
> Fix trick_exclude_typename

- include/trick/swig/cast_as.i
- libexec/trick/convert_swig
> Fix template regex in convert_swig

- libexec/trick/convert_swig
> Fully qualify TRICK_SWIG_TEMPLATE identifiers

- trick_sims/SIM_wheelbot/S_define
- trick_sims/SIM_wheelbot/models/Control/include/PIDController.hh
- trick_sims/SIM_wheelbot/models/Control/include/differentialDriveController.hh
- trick_sims/SIM_wheelbot/models/Control/src/PIDController.cpp
- trick_sims/SIM_wheelbot/models/Control/src/differentialDriveController.cpp
Files added:
trick_sims/SIM_wheelbot/models/Control/include/PIDController.hh
trick_sims/SIM_wheelbot/models/Control/src/PIDController.cpp
Files modified:
trick_sims/SIM_wheelbot/models/Control/include/differentialDriveController.hh
trick_sims/SIM_wheelbot/models/Control/src/differentialDriveController.cpp
trick_sims/SIM_wheelbot/S_define
Changes made:
Improved PIDController getOutput functionality as requested by John Penn.
Changed PIDController initialization to be object oriented rather than pointer oriented as requested by Scott Fennell
> Pidcontroller wheelbot

- trick_sims/SIM_wheelbot/README.md
- trick_sims/SIM_wheelbot/RUN_test/input.py
- trick_sims/SIM_wheelbot/models/Control/README.md
- trick_sims/SIM_wheelbot/models/Control/include/vehicleController.hh
- trick_sims/SIM_wheelbot/models/Control/src/vehicleController.cpp
- trick_sims/SIM_wheelbot/models/GUIControl1/Makefile
- trick_sims/SIM_wheelbot/models/GUIControl1/README.md
- trick_sims/SIM_wheelbot/models/GUIControl1/src/trick/HomeDisplay.java
- trick_sims/SIM_wheelbot/models/Vehicle/include/vehicleOne.hh
- trick_sims/SIM_wheelbot/models/Vehicle/src/vehicleOne.cpp
Purpose:
The code review with John Penn highlighted some minor changes that were required. I also added a lot of in-line documentation for the ease of reading the code. 
Files Changed:
trick_sims/SIM_wheelbot/RUN_test/input.py
trick_sims/SIM_wheelbot/models/Control/include/vehicleController.hh
trick_sims/SIM_wheelbot/models/Control/src/vehicleController.cpp
trick_sims/SIM_wheelbot/models/README.md
trick_sims/SIM_wheelbot/models/Control/README.md
trick_sims/SIM_wheelbot/models/Vehicle/include/vehicleOne.hh
trick_sims/SIM_wheelbot/models/Vehicle/src/vehicleOne.cpp
New Files:
trick_sims/SIM_wheelbot/models/GUIControl1/Makefile
trick_sims/SIM_wheelbot/models/GUIControl1/README.md
trick_sims/SIM_wheelbot/models/GUIControl1/src/trick/HomeDisplay.java
> Home Button and End Behavior Improvments to Wheelbot

- trick_source/codegen/Interface_Code_Gen/main.cpp
> #1041 filter -W workaround for ICG linking to LLVM 10 libclang-cpp.so

- .github/workflows/test.yml
- docs/documentation/install_guide/Install-Guide.md
closes #1048 and closes #1050 
Update java version, check/update dependencies and various other improvements.
> 1048 and 1050 update Install Guide

- trick_source/codegen/Interface_Code_Gen/PrintAttributes.cpp
> 1036 1007 only enable  cpp11 in Makefile_io_src when needed

- trick_source/codegen/Interface_Code_Gen/CommentSaver.cpp
- trick_source/codegen/Interface_Code_Gen/FieldVisitor.cpp
- trick_source/codegen/Interface_Code_Gen/HeaderSearchDirs.cpp
- trick_source/codegen/Interface_Code_Gen/PrintAttributes.cpp
- trick_source/codegen/Interface_Code_Gen/Utilities.cpp
> issue 1065 llvm 11 support 

- trick_source/trick_swig/swig_double.i
- trick_source/trick_swig/swig_int.i
> Add units to swig_int and swig_double

- README.md
- autoconf/configure.ac
- configure
- test/SIM_demo_inputfile/models/InputProcessSimObject/src/InputProcessSimObject.cpp
- test/SIM_test_sched/models/sched/src/sched_amf.c
- test/SIM_test_sched/models/sched/src/sched_async.c
- trick_source/data_products/DPX/test/unit_test/makefile
> 1076 why path dumb

- .github/workflows/test_linux.yml
- include/trick/Sie.hh
- include/trick/sie_c_intf.h
- share/trick/sim_objects/default_trick_sys.sm
- trick_source/sim_services/Sie/Sie.cpp
- trick_source/sim_services/Sie/sie_c_intf.cpp
- trick_source/sim_services/VariableServer/VariableServerThread_commands.cpp
closes #1086
closes #1088
closes #1089
> tv dynamic allocations post initialization and test update

- trick_source/sim_services/DataRecord/DataRecordGroup.cpp
> Call follow_address_path for DR_Changes triggers

- trick_source/codegen/Interface_Code_Gen/HeaderSearchDirs.cpp
> Check paths against TRICK_HOME in HeaderSearchDirs

- include/trick/ExternalApplication.hh
- include/trick/MonteCarlo.hh
- include/trick/checkpoint_map.hh
- include/trick/checkpoint_pair.hh
- include/trick/checkpoint_queue.hh
- include/trick/checkpoint_sequence_stl.hh
- include/trick/checkpoint_stack.hh
- include/trick/swig/swig_extend_str.i
- include/trick/swig/swig_int_templates.hh
- include/trick/swig/swig_int_typemap.i
- share/trick/sim_objects/default_trick_sys.sm
- trick_source/sim_services/ExternalApplications/ExternalApplication.cpp
- trick_source/sim_services/ExternalApplications/ExternalApplication_c_intf.cpp
- trick_source/sim_services/MemoryManager/test/MM_write_checkpoint.cc
- trick_source/sim_services/MonteCarlo/MonteCarlo_c_intf.cpp
- trick_source/sim_services/MonteCarlo/MonteCarlo_funcs.cpp
- trick_source/trick_swig/units_attach.i
> 1093 c str

- include/trick/ExternalApplication.hh
- trick_source/sim_services/ExternalApplications/ExternalApplication.cpp
resolves issue with pull request #1119
> Void ptr external application

- trick_source/sim_services/MonteCarlo/MonteCarlo_receive_results.cpp
Closes #1192
@tfleming-osr How's this look?
> Always requeue timed-out MonteCarlo runs

- share/trick/trickops/TrickWorkflow.py
> Replace deprecated yaml.load() with yaml.safe_load()

- docs/documentation/simulation_capabilities/Data-Record.md
- docs/tutorial/ATutNumericSim.md
- docs/tutorial/TutVariableServer.md
> Tutorial suggestions

- .github/workflows/test_linux.yml
- trick_source/codegen/Interface_Code_Gen/ClassVisitor.cpp
- trick_source/codegen/Interface_Code_Gen/TranslationUnitVisitor.cpp
> 1279 llvm 14

- trick_source/codegen/Interface_Code_Gen/main.cpp
- trick_source/data_products/DPX/test/unit_test/makefile
closes #1283 
closes #1284 
closes #1285
> 1283 apple silicon

- trick_source/sim_services/VariableServer/vs_format_ascii.cpp
> Omit cv_convert_double for trivial conversions

- include/trick/MyCivetServer.hh
- include/trick/WebSocketSession.hh
- trick_sims/Cannon/models/httpMethods/TimeSession.cpp
- trick_sims/Cannon/models/httpMethods/TimeSession.hh
- trick_source/web/CivetServer/include/VariableServerSession.hh
- trick_source/web/CivetServer/src/MyCivetServer.cpp
- trick_source/web/CivetServer/src/VariableServerSession.cpp
- trick_source/web/CivetServer/src/http_GET_handlers.cpp
> #1315 parse websocket msg len for correct data

- trick_source/sim_services/MemoryManager/MemoryManager_clear_memory.cpp
> Revert "In MemoryManager_clear_memory.cpp call delete_var with destroy flag==…"

- include/trick/DataRecordDispatcher.hh
- trick_source/sim_services/DataRecord/DataRecordDispatcher.cpp
- trick_source/sim_services/DataRecord/DataRecordGroup.cpp
Fixes a race condition as described in #1290 
Closes #1290
> Race condition patch

- .github/workflows/test_macos.yml
- trick_source/data_products/DPX/test/unit_test/makefile
- trick_source/sim_services/Clock/test/Makefile
- trick_source/sim_services/Executive/test/Makefile
- trick_source/sim_services/Integrator/test/Makefile
- trick_source/sim_services/MonteCarlo/test/Makefile
- trick_source/sim_services/ScheduledJobQueue/test/Makefile
- trick_source/sim_services/Timer/test/Makefile
- trick_source/trick_utils/SAIntegrator/unittest/Makefile
- trick_source/trick_utils/comm/test/Makefile
- trick_source/trick_utils/interpolator/test/Makefile
- trick_source/trick_utils/math/test/Makefile
- trick_source/trick_utils/unicode/test/Makefile
- trick_source/trick_utils/units/test/makefile
> replace GTEST_HAS_TR1_TUPLE with -std=c++11

- trick_source/sim_services/MemoryManager/MemoryManager_ref_assignment.cpp
Fixes:
https://github.com/nasa/trick/issues/1335
> Fix issue with writing to an array of std::strings.

- trick_source/er7_utils/integration/core/src/base_integration_group.cc
- trick_source/er7_utils/interface/include/alloc.hh
- trick_source/sim_services/InputProcessor/IPPythonEvent.cpp
- trick_source/sim_services/MemoryManager/MemoryManager_clear_memory.cpp
https://github.com/nasa/trick/issues/1301
> Multiple fixes to address 1301

- .github/workflows/report_linux.yml
- .github/workflows/test_linux.yml
I only added this configuration to Oracle Linux, we don't need to test it on every single OS
> Add configuration without er7 integrators to CI pipeline

- trick_source/java/Makefile
> Increase retry count for maven

- .github/workflows/test_linux.yml
> 1342 noerinteg ci pipeline

- trick_source/sim_services/MonteCarlo/MonteCarlo_receive_results.cpp
> Ensure MC slaves are set to ready after timeouts

- .github/workflows/alt_linux_distros.yml
- .github/workflows/code_coverage.yml
- .github/workflows/test_32.yml
- .github/workflows/test_32_oracle.yml
- .github/workflows/test_linux.yml
- .github/workflows/test_linux_py2.yml
- .github/workflows/trickops.yml
> Refactor workflow distros and workflow python matrix (#1400)

- test/SIM_test_varserv/models/test_client/test_client.cpp
- Add freeze test to SIM_test_varserv
- Make mode test more comprehensive
> Improvements to SIM_test_varserv

- docs/documentation/building_a_simulation/Model-Source-Code.md
- libexec/trick/pm/html.pm
- test/SIM_python_namespace/RUN_test/unit_test.py
- test/SIM_python_namespace/S_define
- test/SIM_python_namespace/models/TrickFood.hh
> Handle empty PYTHON_MODULE in header comment

- test/SIM_test_varserv/models/test_client/test_client.cpp
- trick_source/sim_services/VariableServer/vs_format_ascii.cpp
> 1444 patch - Fix undefined behavior in vs_format_ascii

- trick_source/trick_swig/units_attach.i
> Update swig interface to work python 3.11

- trick_source/codegen/Interface_Code_Gen/main.cpp
> Fix c++20 flag for LLVM 10

- trick_source/trick_swig/Makefile
> Ensure swig target folder is created

- .github/workflows/code_coverage.yml
- .github/workflows/test_linux.yml
- docs/howto_guides/How-To-Guides.md
- docs/howto_guides/How-To-Python-Virtual-Environment.md
> Add HOWTO for Python VIrtual Environment.

- include/trick/IntegLoopSimObject.hh
> Add va_end() to close corresponding va_start(). #1563

- trick_source/sim_services/Integrator/src/IntegLoopScheduler.cpp
> Fix status return logic in process_dynamic_events. #1557

- trick_source/sim_services/InputProcessor/IPPython.cpp
- trick_source/trick_swig/sim_services.i
Added input file SHA1 info print out when running a sim with -d option (basically verifying the input)
> checksum enhancement for -d option

- docs/howto_guides/How-To-Python-Virtual-Environment.md
Add conda instruction to "How to Setup a Virtual Python Environment"
> Add conda instruction to "How to Setup a Virtual Python Environment"

- include/trick/Executive.hh
- trick_source/sim_services/Executive/Executive_init.cpp
- trick_source/sim_services/Executive/Executive_shutdown.cpp
Added system cpu & initialization time and updated sim/cpu time with both user and system cpu time for the run stats.
> 1592 send hs run stats improvement

- trick_source/codegen/Interface_Code_Gen/ClassVisitor.cpp
- trick_source/codegen/Interface_Code_Gen/ClassVisitor.hh
- trick_source/codegen/Interface_Code_Gen/ConstructValues.cpp
- trick_source/codegen/Interface_Code_Gen/ConstructValues.hh
Updated not to add "friend class" to embedded private list so it can be accessed.
> Updated not to add "friend class" to embedded private list so it can be accessed. 

- trick_source/sim_services/Executive/Executive_signal_handler.cpp
This pull request fixes a problem that only happens on MacOS, because of security updates to MacOS.
If a process starts a child process that attempts to attach a debugger, Apple's Security Integrity Protection (SIP) will kill it and the child process. Presumably this is for security. But we can attach a debugger from an independent process. So if your input file calls trick.exec_set_attach_debugger(1), and you get a SIGSEGV the signal handler will start LLDB, but not attach it to the parent process. It does this only to suspend the process so that you can attach LLDB to it from another terminal, via an independent process ( which works).
For trick.exec_set_stack_trace(0), LLDB is not even needed.
> Fix "Fix the Mac debugger attachment on segfault" #1386

- include/trick/Executive.hh
- trick_source/sim_services/Executive/Executive_init.cpp
- trick_source/sim_services/Executive/Executive_shutdown.cpp
Added additional resource usage info for sim run.
> More rusage info added to the end of the run summary output enhancement

- share/trick/trickops/TrickWorkflow.py
> Protect TrickOps progres bar from divide by zero

- libexec/trick/sie_concat
Updated to go through all trickified classes.resource if found and don't die on any if not found.
> 1652 add trickified to default sie generation

- trick_sims/SIM_lander/RUN_test/input.py
This is a very simple fix to sim lander. Variables names were changed in code but I apparently forgot to update the input file.
> Fix SIM_lander input file.

- docs/documentation/web/Webserver.md
Removed double quotes for port number and added some inline code syntax highlighting with back-ticks.
> Removed double quotes for port number and added some inline code syntax highlighting with back-ticks.

- include/trick/message_proto.h
- trick_source/sim_services/Message/Message_c_intf.cpp
Implemented C Interface for Message Subscribers, I did.
> Implemented C Interface for Message Subscribers.

- docs/documentation/building_a_simulation/Simulation-Definition-File.md
Just a quick documentation update
> 1722 documentation placeholder instead of link

- docs/documentation/install_guide/Install-Guide.md
Updated Trick Install Guide for macOS (for both Intel-based and Apple Silicon), added sections for building Clang & LLVM, SWIG, and user notes for making a fresh trick installation on Apple Silicon mac.
> Updated Trick Install Guide for macOS.

- .github/workflows/python_tests_linux.yml
- .github/workflows/test_linux.yml
Addressing configuration issues with CentOS CI
> CentOS CI Fix

- libexec/trick/convert_swig
- test/SIM_test_ip/S_define
- test/SIM_test_ip/models/test_ip/include/ArrayTemplate.hh
> Added swig support for templates with array parameters

- docs/developer_docs/DesConvertSwig.md
- libexec/trick/convert_swig
- test/SIM_test_ip/RUN_test/unit_test.py
- test/SIM_test_ip/models/test_ip/include/ClassOfEverything.hh
- test/SIM_test_ip/models/test_ip/include/FooB.hh
- test/SIM_test_ip/models/test_ip/include/FooD.hh
- test/SIM_test_ip/models/test_ip/include/IfndefSwigTest.hh
- test/SIM_test_ip/models/test_ip/include/TemplateTest.hh
Updated convert_swig to account for template directive changes in SWIG 4
> SWIG 4 Template Directive Changes

- include/trick/Integrator.hh
- include/trick/integrator_c_intf.h
- trick_source/sim_services/Integrator/src/IntegLoopScheduler.cpp
- trick_source/sim_services/Integrator/src/Integrator.cpp
- trick_source/sim_services/Integrator/src/Integrator_C_Intf.cpp
Added "target_integ_time" to Integrator class and C APIs. It can be useful to know the final integration time even during intermediate steps.
> Need a bit more info in Integrator class

- trick_source/sim_services/Message/MessagePublisher.cpp
- trick_source/sim_services/Message/message_publish_standalone.cpp
Add sub second information to message time stamps.
> Added sub second information to message time stamps.

- trick_source/sim_services/MemoryManager/MemoryManager_delete_var.cpp
fixes https://github.com/nasa/trick/issues/1777
> Add deletions to tracking list if malloc or new

- trick_source/sim_services/VariableServer/VariableServerListenThread.cpp
> Fixed error message for sims with the same port number

- trick_source/java/src/main/java/trick/sie/utils/SearchPanel.java
- trick_source/java/src/main/java/trick/sie/utils/Searcher.java
If you want your searches greedy you can have them greedy.
> 1746 trick view variable search causes large spike in cpu usage

- trick_source/sim_services/ScheduledJobQueue/ScheduledJobQueue.cpp
- trick_source/sim_services/ScheduledJobQueue/test/ScheduledJobQueue_test.cpp
Corrected an error when calculating the index during a job queue push.
> Fixed new job index calc

- README.md
Cleaned up the display on the github page.
> Fixing a minor nuisance

- docs/documentation/building_a_simulation/Model-Source-Code.md
- libexec/trick/convert_swig
- test/SIM_swig_template_scoping/S_overrides.mk
- test/SIM_swig_template_scoping/models/Classes.hh
- test_sims.yml
> Improve SWIG %template directive scoping - take 2

- .github/workflows/report_alt_linux_distros.yml
- .github/workflows/report_linux.yml
- .github/workflows/report_linux_py2.yml
- .github/workflows/report_macos.yml
Changed test report version back to v1 as it was changed to v4 by mistake
> Changed test report version to v1

- trick_source/java/src/main/java/trick/common/ui/panels/FindBar.java
- trick_source/java/src/main/java/trick/sie/SieApplication.java
- trick_source/java/src/main/java/trick/simcontrol/SimControlApplication.java
Customized FindBar class that used to extend JXFindBar now extends JPanel to avoid the compatibility issue between Swing and newer JDK.
> Customized FindBar class that used to extend JXFindBar now extends JPanel.

- trick_source/codegen/Interface_Code_Gen/FieldDescription.cpp
Updated not to process *io as for io(<io_spec>).
> Updated not to process *io as for io(<io_spec>).

- trick_source/sim_services/FrameLog/FrameLog.cpp
Updated to include pre_integration job frame logging.
> Updated to include pre_integration job frame logging.

- trick_source/sim_services/DataTypes/testing/makefile
> Update testing build to use C++14 which is required for gtest.

- trick_source/java/src/main/java/trick/common/ui/UIUtils.java
- trick_source/java/src/main/java/trick/common/ui/panels/AnimationPlayer.java
- trick_source/java/src/main/java/trick/simcontrol/SimControlApplication.java
> Made 2 frame gifs work

- trick_source/java/src/main/java/trick/common/RunTimeTrickApplication.java
- trick_source/java/src/main/java/trick/common/TrickApplication.java
- trick_source/java/src/main/java/trick/tv/TVApplication.java
Turned on look and feel for tv
> Turned on look and feel for tv

- trick_source/codegen/Interface_Code_Gen/FieldVisitor.cpp
- trick_source/codegen/Interface_Code_Gen/main.cpp
> Updated to support llvm 20

- trick_source/sim_services/MemoryManager/test/.gitignore
- trick_source/trick_utils/trick_adt/test/.gitignore
Adding missing items to .gitignore to MM test and missing .gitignore file to trick_adt test.
> Adding missing items to .gitignore to MM test and missing .gitignore file to trick_adt test.

- share/trick/swig/shortcuts.py
- trick_source/codegen/Interface_Code_Gen/PrintFileContents10.cpp
Updated to only compute offset for virtual inherited public fields in init_attr functions in io_ code.
> Updated to only compute offset for virtual inherited public fields.

- trick_source/java/src/main/java/trick/jobperf/FrameRecord.java
- trick_source/java/src/main/java/trick/jobperf/FrameViewCanvas.java
- trick_source/java/src/main/java/trick/jobperf/JobExecutionEvent.java
- trick_source/java/src/main/java/trick/jobperf/JobPerf.java
- trick_source/java/src/main/java/trick/jobperf/JobSpecification.java
- trick_source/java/src/main/java/trick/jobperf/JobSpecificationMap.java
- trick_source/java/src/main/java/trick/jobperf/JobStats.java
- trick_source/java/src/main/java/trick/jobperf/JobStatsViewCanvas.java
- trick_source/java/src/main/java/trick/jobperf/JobStatsViewWindow.java
- trick_source/java/src/main/java/trick/jobperf/TraceViewCanvas.java
- trick_source/java/src/main/java/trick/jobperf/TraceViewMenuBar.java
- trick_source/java/src/main/java/trick/jobperf/TraceViewWindow.java
Add testing of timeline data, and refactoring. Still has problem with job order in Arraylist of frame Records.
> Jperf refactor

- docs/howto_guides/Realtime-Best-Practices.md
> Update Realtime-Best-Practices to mention trick-jperf

- libexec/trick/convert_swig
Added enum struct support the same way as enum class.
> Added enum struct support the same way as enum class.

- libexec/trick/convert_swig
> Enum struct support

- trick_source/sim_services/MemoryManager/MemoryManager_ref_attributes.cpp
- trick_source/sim_services/MemoryManager/MemoryManager_ref_dim.cpp
- trick_source/sim_services/VariableServer/VariableReference.cpp
Added a check for unconstrained dimensions boundary.
> Added a check for unconstrained dimensions boundary.

- include/trick/swig/trick_swig.i
Changed the swig version check from 4.0.0 to 3.0.8 fro std_wstring.i
> Changed the swig version check for std_wstring.i.

- trick_source/sim_services/DataRecord/DataRecordGroup.cpp
> Fix DR_Changes_Step

- trick_source/sim_services/MemoryManager/MemoryManager_ref_attributes.cpp
- trick_source/sim_services/MemoryManager/MemoryManager_ref_dim.cpp
Updated to allow to use index [0] on regular pointer as an equivalent to ->.
> Updated to allow to use index [0] on regular pointer.

- trick_source/java/src/main/java/trick/common/RunTimeTrickApplication.java
- trick_source/java/src/main/java/trick/common/TrickApplication.java
- trick_source/java/src/main/java/trick/common/utils/VariableServerConnection.java
- trick_source/java/src/main/java/trick/simcontrol/SimControlApplication.java
- trick_source/java/src/main/java/trick/tv/TVApplication.java
Updated the TV app to have a shorter timeout when attempting to connect to the var server, similar to the Sim Control Panel.
> Updated the TV app to have a shorter timeout when attempting to connect to the var server.
