nasa/trick

include/trick/MonteCarlo.hh, include/trick/MonteVarCalculated.hh, include/trick/MonteVarFile.hh, include/trick/MonteVarFixed.hh, include/trick/MonteVarRandom.hh, include/trick/swig/trick_swig.i, trick_source/sim_services/MonteCarlo/MonteCarlo_funcs.cpp
Added duplicate name protection on add_variable and get_variable
mechanism for getting MonteVar * derived types so that those dispersion
settings can be changed once they go out of scope.
=> MonteCarlo add_variable duplicate protection and get_variable functionality

trick_source/sim_services/MonteCarlo/MonteCarlo_funcs.cpp
When runs reduced via successive calls to set_num_runs, instead of using
pop_front() and front(), use pop_back() and back()
Refs #304
=> Fixed indexing problem when reducing number of monte carlo runs

trick_source/trick_swig/units_attach.i
The filename output when units are converted failed in Python 3 due to using PyString_AsString. I used the same procedure that is used previously in the same function to fix the error.
=> Fix filename output in attach_units for Python 3

include/trick/MonteVar.hh, include/trick/MonteVarFile.hh, include/trick/MonteVarFixed.hh, trick_source/sim_services/MonteCarlo/MonteVarFile.cpp, trick_source/sim_services/MonteCarlo/MonteVarFixed.cpp
Added set_unit mechanism to MonteVar baseclass. Added MonteVar's derived
classes setters where appropriate to facilitate changing inputs after
the instance of MonteVar has already been constructed. Fleshed out
MonteVarFile destructor to remove memory leaks.
=> Added MonteVar setters where appropriate

bin/pm/make_makefile.pm
Change the way the simulation object library is generated to eliminate long paths at the beginning of each file going into the argument list for the ar command. The make command on macOS is sensitive to the length of the argument list, and the ar command would fail when the argument list gets north of 200,000 characters.
=> Reduced size of generated argument list for simulation library creation

trick_source/codegen/Interface_Code_Gen/makefile
=> Re-add '-std=c++11' in ICG CXXFLAGS when Clang version >= 3.5

trick_source/java/src/trick/simcontrol/utils/SimControlActionController.java
Entering extremely large values into the maximum value field of the throttle GUI caused the GUI to freeze. Imposing a cap of 1000 to the maximum value prevents the GUI from freezing.
=> Capped the maximum throttle value to 1000.

include/trick/MonteCarlo.hh, trick_source/sim_services/MonteCarlo/MonteCarlo.cpp, trick_source/sim_services/MonteCarlo/MonteCarlo_funcs.cpp, trick_source/sim_services/MonteCarlo/MonteCarlo_initialize_sockets.cpp, trick_source/sim_services/MonteCarlo/MonteCarlo_slave_init.cpp
Some classes were still calling socket_init which had been removed. Replaced those calls with tc_init.
Make compiled and make test successfully ran all tests. Jenkins should be happy now.
This pull requests references the following issue: #398
=> Replaced socket_init calls with tc_init.

libexec/trick/convert_swig
Fixes issue https://github.com/nasa/trick/issues/468.
This is not a complete fix. Template template parameters (e.g., `template< template<class> class T> class Foo ...`) aren't parsed correctly.
=> Fixes #468

include/trick/MonteVarFile.hh, trick_source/sim_services/MonteCarlo/MonteVarFile.cpp, trick_source/sim_services/MonteCarlo/MonteVarFixed.cpp
This pull request is in response to #316.
By converting data file traversal from strtold to strtok, it is possible to accept non numerical values in data files. If sending a string, it may be necessary to surround the string with "quotations". Non_numerical values  can also not contain spaces or tabs.
=> Non-numerical values can now be used in Monte Carlo data files.

libexec/trick/pm/parse_s_define.pm
**Is there somewhere to put some unit tests for this sort of fix?**
Rather than just searching for the first pair of curly braces to find a
sim object's constructor, parse any member initializer list that is
present. Fixes #443.
=> Improve handling of sim object member initializers

include/trick/MonteVarFile.hh, trick_source/sim_services/MonteCarlo/MonteVarFile.cpp
Uses seekg() and tellg() to save and restore the position of the file stream.
This pull request is in response to issue #432.
=> Implemented a fix for multiple concurrent file handles.

libexec/trick/make_makefile_src, trick_source/codegen/Interface_Code_Gen/PrintAttributes.cpp
This will ensure objects are rebuilt only due to a missing dependency
file, not a newer one.
Fixes #501.
=> Make object .d files order-only prerequisites

trick_source/sim_services/MonteCarlo/test/MonteCarlo_exceptions.cpp, trick_source/sim_services/MonteCarlo/test/MonteCarlo_test.cpp
A change I had made to how the get_next_value() function returns values invalidated this unit test. This error stemmed from the changes I made in c8f916e8182dc9b4d9c13b187442e295e67c9290 that allowed non numerical values to be used in the data file. 
Originally, trailing 0s were being stripped before the value was returned.
Now, the value present in the data file is the exact value returned by get_next_value().
I have modified the unit test to reflect this new behavior.
=> Modified unit tests to account for new logic.

Makefile
Hurray!  A warning has been added to the "make install" target that warns users if they haven't compiled Trick first.
This pull request is in reference to issue #495.
=> Added warning to 'make install'.

trick_source/codegen/Interface_Code_Gen/FieldDescription.cpp
The `io` field of `FieldDescription` takes a default value of 15. In
`FieldDescription::parseComment`, it may be updated as specified in the comment
text. There are 4 possible cases:
1) Neither IO attributes nor checkpoint IO attributes are found in the comment
2) IO attributes are found in the comment, but checkpoint IO attributes are not
3) Checkpoint IO attributes are found in the comment, but IO attributes are not
4) Both IO attributes and checkpoint IO attributes are found in the comment
In case 2, the IO attributes are copied into the checkpoint IO attributes by the
statement `io |= (io << 2)`. However, this also erroneously runs in case 1,
causing the default value of 15 to change to 63.
By testing `io_found == true`, this logic occurs only in case 2.
Fixes #568
=> Only left-shift `FieldDescription::io` when `io_found == true`

include/trick/UnitTest.hh, trick_source/sim_services/UnitTest/UnitTest.cpp
I noticed that simulation exit codes do not reflect Trick UnitTest status. So, I added the following:
- A new class member flag in the UnitTest class called exit_code_enabled. This is a boolean which is false by default. We are open to make this on by default if this doesn't change expected behavior on the Trick side.
- A new class method which toggles this boolean.
- A new logic block that will call exec_terminate_with_return if two conditions are met: exit_code_enabled is true, num_failures is greater than 0
To demonstrate this in action, apply the following patch to trick_sims/SIM_Ball++_L1/RUN_test/unit_test.py:
```diff
diff --git a/trick_sims/SIM_Ball++_L1/RUN_test/unit_test.py b/trick_sims/SIM_Ball++_L1/RUN_test/unit_test.py
index 7a97255..ec362fe 100644
--- …
```
=> Unit test exit code

include/trick/ClassicCheckPointAgent.hh, include/trick/IntegLoopManager.hh, include/trick/IntegLoopScheduler.hh, include/trick/JobData.hh, include/trick/MemoryManager.hh, include/trick/ScheduledJobQueue.hh, include/trick/Scheduler.hh, include/trick/SimObject.hh, include/trick/message_type.h, include/trick/parameter_types.h, include/trick/sim_mode.h, trick_source/er7_utils/integration/beeman/src/beeman_integrator_constructor.cc, trick_source/er7_utils/integration/core/include/generalized_position_derivative.hh, trick_source/er7_utils/integration/core/include/integration_controls.hh, trick_source/er7_utils/integration/rkn4/include/rkn4_second_order_ode_integrator.hh, trick_source/er7_utils/interface/include/alloc.hh, trick_source/er7_utils/interface/include/type_traits.hh, trick_source/er7_utils/math/include/n_choose_m.hh, trick_source/er7_utils/math/include/ratio128.hh
Apply the Hammen docs patches to the appropriate files in master.
All this took was
```sh
git format-patch -1 bbdf0f83784e635512d9bdc8d6e039efcb0ec885
git checkout master
git am 0001-Compile-clean-with-clang-Wdocumentation.patch
git am --abort
sed -e 's!trick_source/sim_services/[^/]*/include/!include/trick/!g' 0001-Compile-clean-with-clang-Wdocumentation.patch > 0001-Compile-clean-with-clang-Wdocumentation--fixed.patch
git am 0001-Compile-clean-with-clang-Wdocumentation--fixed.patch
git format-patch -1 ed335ff92695a2584655648abdb99d452792f995
git am 0001-Fixed-a-code-bug-and-a-comment-bug-in-er7_utils-most.patch
```
This preserves the author / commit message while applying it to the (slightly changed) paths.
Resolves #512
=> Port Hammen doxygen documentation fix to Trick 17

autoconf/configure.ac, configure
This fixes 3 known issues with the configure/configure.ac scripts. For the version checks, I went with the given versions in the Install Guide.
I'm not sure why the order of PYTHON_EXTRA_LIBS and PYTHON_EXTRA_LDFLAGS swapped. Anyone know a way to avoid that?
=> Configure fixes

trick_source/sim_services/Executive/Executive.cpp
Trick's backtrace or debugger attach functionality fails on systems like Ubuntu where the use of [`ptrace(2)`] is restricted. Where it is defined, use the [`prctl(2)`] call `PR_SET_PTRACER` with the argument `PR_SET_PTRACER_ANY` to allow any process to attach.
Fixes #616.
[`ptrace(2)`]: http://man7.org/linux/man-pages/man2/ptrace.2.html
[`prctl(2)`]: http://man7.org/linux/man-pages/man2/prctl.2.html
=> Fix debugger attach when ptrace is restricted

libexec/trick/java/lib/Makefile
Curl can fail transiently. Have it retry a few times before giving up.
```
make[2]: Entering directory '/home/gitlab-runner/builds/272e0b41/0/path/to/trick/libexec/trick/java/lib'
curl -O http://repo.maven.apache.org/maven2/org/jdesktop/bsaf/bsaf/1.9.2/bsaf-1.9.2.jar
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0curl: (6) Could not resolve host: repo.maven.apache.org
Makefile:24: recipe for target 'bsaf-1.9.2.jar' failed
make[2]: *** [bsaf-1.9.2.jar] Error 6
make[2]: Leaving directory …
```
=> Retry curl operations to avoid transient failures.

trick_source/sim_services/MemoryManager/adef_parser.l, trick_source/sim_services/MemoryManager/adef_parser.y, trick_source/sim_services/MemoryManager/ref_parser.l, trick_source/sim_services/MemoryManager/ref_parser.y, trick_source/sim_services/Message/MessageThreadedCout.cpp
Bison and Flex both generate warnings from generated code. The code is fine.
void * Trick::MessageThreadedCout::thread_body() needs to return a value, specifically NULL;
=> Warning fixes

trick_source/java/src/trick/common/utils/DataReader.java, trick_source/java/src/trick/dataproducts/plot/utils/TrickXYPlot.java
One was a problem plotting flat-line data ( f(x) = 0 ), because max and min of the y axis were being set to 0, which jfreeChart don't tolerate.
Other is a missing check for missing units.
=> Two Java plot fixes

trick_source/java/src/trick/dataproducts/trickqp/utils/ProductColumn.java, trick_source/java/src/trick/dataproducts/trickqp/utils/ProductMeasurement.java, trick_source/java/src/trick/dataproducts/trickqp/utils/ProductVar.java, trick_source/java/src/trick/dataproducts/trickqp/utils/ProductXMLCreator.java, trick_source/java/src/trick/dataproducts/trickqp/utils/TrickQPActionController.java
Trick-qp initialized units elements to "--" which is incorrect.
The <units> element optionally specifies units to which the recorded should be converted.
When non-null a <units> specification should be generated. When null the <units> element should not be generated. The bogus <units> -- <\units> was causing the fermi tape generation tool to crash because it was attempting to convert "m/s2" etc. to "--".
=> Fix incorrect initialization of units in trick-qp.

trick_source/trick_utils/math/src/deuler_123.c, trick_source/trick_utils/math/src/deuler_123_quat.c, trick_source/trick_utils/math/src/deuler_132.c, trick_source/trick_utils/math/src/deuler_132_quat.c, trick_source/trick_utils/math/src/deuler_213.c, trick_source/trick_utils/math/src/deuler_213_quat.c, trick_source/trick_utils/math/src/deuler_231.c, trick_source/trick_utils/math/src/deuler_231_quat.c, trick_source/trick_utils/math/src/deuler_312.c, trick_source/trick_utils/math/src/deuler_312_quat.c, trick_source/trick_utils/math/src/deuler_321.c, trick_source/trick_utils/math/src/deuler_321_quat.c
Previous code generated FP div by zero error.
This fix returns NaNs in each of the angle elements.
=> Replace unreliable 'divide-by-zero' way of generating NaNs with math.h NAN in *deuler* routines.

trick_source/sim_services/DataRecord/DataRecordDispatcher.cpp
This fixes the problem described in Issue 685.
=> Fix lockup when running Valgrind. Ref #685

trick_source/data_products/Log/multiLog.cpp, trick_source/sim_services/DataTypes/src/MemMgr.cpp
We know how many more elements we are going to push into ```listLogGroupIterators_``` so use that to our advantange and reserve inadvance to save on re-allocation costs.
=> Vector Optimize to Save on Re-Allocation costs.

trick_source/trick_utils/comm/src/tc_init_udp_client.c, trick_source/trick_utils/comm/src/tc_init_udp_server.c
The TCP_NODELAY socket option disables Nagle's algorithm on TCP sockets,
improving latency at the cost of throughput. This option is
TCP-specific, and it is an error to use it on any other kind of socket,
including UDP. It is also unnecessary, since UDP is datagram-based and
does not buffer data to be transmitted.
See #728
=> Disable setting TCP_NODELAY on UDP sockets

trick_source/codegen/Interface_Code_Gen/TranslationUnitVisitor.cpp
@alexlin0 [This change](https://github.com/nasa/trick/commit/ba75f6ff375becf1496b801f5252942663a56c5f#diff-cb10579d3a42a4438bf9bbb4612277e2L49), made in response to llvm removing `getRBraceLoc`, subtly altered the forward-declaration-detection logic, which has resulted in #724. I think my fix is correct, but I'd appreciate your review. 
Fixes #724
@genti337
=> Correct forward-declaration-detection logic in ICG

trick_source/codegen/Interface_Code_Gen/PrintAttributes.cpp, trick_source/codegen/Interface_Code_Gen/PrintAttributes.hh
[`isHeaderExcluded`](https://github.com/nasa/trick/blob/b9278c4a729d9bec1cfe7974629f3d90116f9fda/trick_source/codegen/Interface_Code_Gen/PrintAttributes.cpp#L513) checks a number of things to determine if a header file should be processed by ICG. Of concern here are entries in `TRICK_EXT_LIB_DIRS`, which indicate files that have been Trickified. For these files, we do not want to produce I/O code, as that will have already been done during Trickification. However, we still want class/enum data in S_sie.resource so that Trickified member type information is available to TrickView. 
5285f1a72ee8d172acd7b698534549a4c3b64abd replaced [`isFileIncluded`](https://github.com/nasa/trick/blob/b9278c4a729d9bec1cfe7974629f3d90116f9fda/trick_source/codegen/Interface_Code_Gen/PrintAttributes.cpp#L116) …
=> Include Trickified classes/enums in S_sie.resource

bin/trick-CP
I didn't see a way to specify a certain directory for trick-CP to build. If that already exists somehow then this pull request is not necessary.
In scenarios where one wants to build many SIM directories, it is a bit cumbersome to `cd` to all of them and then build. I implemented a change to `trick-CP` to allow the `-C/--directory` option to specify a build directory. This is the same feature that `make` has.
Now one can do the following command:
```bash
path/to/trick-CP -C path/to/SIM_directory
```
without first having to `cd` to the path that contains the S_define.
I've tested that this works for the existing sims in Trick by editing `trick_sims/makefile` in the following way:
```diff
1 diff --git a/trick_sims/makefile b/trick_sims/makefile
2 index 881f9efb..cca3cb94 100644
3 --- …
```
=> Give trick-CP the same -C/--directory option that 'make' has.

libexec/trick/make_makefile_swig, libexec/trick/pm/html.pm, test/SIM_python_namespace/RUN_test/unit_test.py, test/SIM_python_namespace/S_define, test/SIM_python_namespace/S_overrides.mk, test/SIM_python_namespace/models/BarFood.hh, test/SIM_python_namespace/models/FooFood.hh, test/SIM_python_namespace/models/FooInnerFood.hh, test/SIM_python_namespace/models/FooYummyFood.hh, test/makefile
Adding back a lost capability, but better this time.  The user can now
specify a python module name where the class and functions will be
visible in python.  With care the user can mimic the C++ namespaces their
models reside in, but it isn't perfect nor automatic.  It's still pretty
neat.
=> Python namespace back from the dead

share/trick/swig/shortcuts.py
This is shorter than the existing trick_mc.mc.add_variable and is accessible through the trick namespace with 'import trick'.
=> Create the shortcut trick.mc_add_variable.

share/trick/pymods/trick/variable_server.py
* Convert string to bytes in `variable_server.py` for Python 3
* Method socket.sendall() (called in `VariableServer.send()`) expects bytes to be sent, rather than a string
* Python 3 stores text strings as unicode (not ASCII) by default
* Therefore, strings must be explicitly converted to bytes for Python 3 compatibility
* This works for both Python 2 and Python 3 (tested on Python 2.7, Python 3.6, and Python 3.7)
=> Python 3 Compatibility for variable_server.py

trick_source/sim_services/Sie/AttributesMap.cpp, trick_source/sim_services/Sie/EnumAttributesMap.cpp, trick_source/sim_services/Sie/Sie.cpp
[`std::endl`] flushes the output stream. The SIE functions were using it multiple times per variable. This can have significant performance impacts on file I/O.
In testing, the `S_sie.resource` file for SIM_parachute was flushed over 14000 times, each resulting in a separate [`write`] system call. With this patch, only ~40 write calls were performed, and writing the file took ~1/3 as long.
For more information, see [C++ Core Guidelines Rule SL.io.50: Avoid `endl`](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#slio50-avoid-endl)
Addresses part of #766.
[`std::endl`]: https://en.cppreference.com/w/cpp/io/manip/endl
[`write`]: http://man7.org/linux/man-pages/man2/write.2.html
=> Replace std::endl with "\n" in SIE

include/trick/MonteCarlo.hh, include/trick/montecarlo_c_intf.h, trick_source/sim_services/MonteCarlo/MonteCarlo_c_intf.cpp, trick_source/sim_services/MonteCarlo/MonteCarlo_dispatch_run_to_slave.cpp, trick_source/sim_services/MonteCarlo/MonteCarlo_master_file_io.cpp, trick_source/sim_services/MonteCarlo/MonteCarlo_spawn_slaves.cpp
@benkirk Alex and I couldn't find a way to correctly split master and slave output with the current options, so he's my proposal for a new feature.
If you checkout this branch, you can use `trick.mc_set_slave_output_directory` to have all the slave's `RUN_*` go wherever you like. Let me know what you think.
Refs #763
=> Add ability to specify MC slave output directory

include/trick/MemoryManager.hh, trick_source/sim_services/MemoryManager/MemoryManager_restore.cpp
@alexlin0 this is a quick and dirty fix for the problem. How can I refine this so that restore_stls is called when it needs to be? @jmpenn are there any defining characteristics that separate a S_default.dat from a checkpoint or are they exactly the same? Will S_default.dat ever need to restore STLs?
=> #776 .dat files don't call restore_stls in checkpoint restore

share/trick/makefiles/Makefile.common
`stdout` goes to `MAKE_out`, as usual, but `stderr` now goes to `MAKE_err`. This makes it easier to parse your errors post-build, as you don't have to grep through the previously-mixed content of `MAKE_out` anymore. In fact, I predict that people will stop looking at `MAKE_out` entirely!
Closes #703
=> Separate stdout and stderr during CP

autoconf/configure.ac, configure, trick_source/data_products/DPX/APPS/FXPLOT/makefile, trick_source/data_products/DPX/APPS/GXPLOT/makefile, trick_source/data_products/DPX/DPC/makefile, trick_source/data_products/DPX/DPM/makefile
If we are on a Mac, use xcrun to find the standard include directories.
Some of the makefiles in data_products look for libxml2 which requires
them to get the same change as the configure script.
=> Add support for Mac's removal of /usr/include #810

include/trick/IPPython.hh, trick_source/codegen/Interface_Code_Gen/FieldDescription.cpp, trick_source/codegen/Interface_Code_Gen/main.cpp, trick_source/sim_services/InputProcessor/IPPython.cpp, trick_source/trick_swig/units_attach.i
Removed checks on dead units conversion messenger.  Units conversion
messages cannot be suppressed.  Added deprecated messages to the functions
that modified the message printouts.
=> Remove suppression of units conversion warnings in 19 #789

libexec/trick/pm/gte.pm
Changed the regular expression that grabs the gcc version to accept
either 1 digit or 2.
=> TRICK_HOST_CPU incorrect with gcc 7 #598

libexec/trick/pm/get_paths.pm, test/SIM_isystem/S_define, test/SIM_isystem/S_overrides.mk, test/SIM_isystem/models/my_code/Foo.cpp, test/SIM_isystem/models/my_code/Foo.hh, test/SIM_isystem/models/third_party/Warning.cpp, test/SIM_isystem/models/third_party/Warning.hh, test/makefile, trick_source/codegen/Interface_Code_Gen/HeaderSearchDirs.cpp, trick_source/codegen/Interface_Code_Gen/HeaderSearchDirs.hh, trick_source/codegen/Interface_Code_Gen/main.cpp
Behold the beauty of cleaner builds. The included example sim is reduced from 26 warnings to 3.
Closes #407
=> Add support for -isystem

autoconf/configure.ac, configure, share/trick/makefiles/Makefile.common, share/trick/makefiles/config_user.mk.in
Added a new configure arugument "--enable-32bit".  If enabled,
TRICK_FORCE_32BIT is automatically set for building Trick and for
all sims built.  Changed the ARCH and added -m32 in the configure
script if 32bit is enabled.  This changes the configure script to
test for 32bit libraries.
=> Make switching to 32bit compile better #829

trick_source/sim_services/JITInputFile/JITInputFile.cpp
Show the detail of DIAGNOSTIC: JITInputfile.
In our project, we found there is a chance JIT will intermittently fail on create the child process.
I think it will more convenient to debug when errno message showing on DIAGNOSTIC.
=> Add debug errno information in the JIT compile

autoconf/configure.ac, configure, libexec/trick/make_makefile_swig
If we can't find python in the configure script then search for
python3.  If python3 is found use python3-config to get the
include directories and libraries.  Call python scripts using the
PYTHON environment variable.
=> configure script fails in RHEL/CentOS 8 #887

include/trick/Integrator.hh, include/trick/integrator_c_intf.h, trick_source/er7_utils/trick/integration/src/trick_integrator.cc, trick_source/sim_services/Integrator/src/Integrator.cpp, trick_source/sim_services/Integrator/src/Integrator_C_Intf.cpp, trick_source/sim_services/Integrator/trick_algorithms/ABM_Integrator.cpp, trick_source/sim_services/Integrator/trick_algorithms/Euler_Cromer_Integrator.cpp, trick_source/sim_services/Integrator/trick_algorithms/Euler_Integrator.cpp, trick_source/sim_services/Integrator/trick_algorithms/MM4_Integrator.cpp, trick_source/sim_services/Integrator/trick_algorithms/NL2_Integrator.cpp, trick_source/sim_services/Integrator/trick_algorithms/RK2_Integrator.cpp, trick_source/sim_services/Integrator/trick_algorithms/RK4_Integrator.cpp, trick_source/sim_services/Integrator/trick_algorithms/RKF45_Integrator.cpp, trick_source/sim_services/Integrator/trick_algorithms/RKF78_Integrator.cpp, trick_source/sim_services/Integrator/trick_algorithms/RKG4_Integrator.cpp
The new state_reset() member function, will only work when Trick is configured to use Trick::Integrator's, that is when configured with ```--disable-er7utils```.
state\_reset() does nothing when Trick is configured with ```--enable-er7utils```, because er7_utils::TrickIntegrator overwrites the state[] array which holds the initial state vector. 
* Add ```state_origin``` data member (a pointer to an array of pointers to double) to class Integrator.
* Add member function ```state_reset()``` to the Integrator class.
* This function ‘undoes’ the last integration of the integrator. It resets the integrator state (and the simulation variables from whence it came) back to its initial state. NOTE: The pointers to the simulation state variables are stored in the new ```state_origin``` array. This …
=> Add ability to reset the integrator state

trick_source/codegen/Interface_Code_Gen/CMakeLists.txt, trick_source/codegen/Interface_Code_Gen/main.cpp, trick_source/codegen/Interface_Code_Gen/makefile
As usual a new LLVM version brings changes.  Found that ICG needs
to be built with c++14.  Also found a couple of API changes in main.
Enclosed the changes in ifdef statements.
=> ICG won't build with LLVM 10.0 #976

autoconf/configure.ac, configure
see #991, #992, and #993. 
To support Ubuntu 20.04 we must support new versions of python and gtest. Python has changed the way it provided libraries using python-config, so adjustments had to be made. I've completely ditched the built in autoconf function for finding python, because it adds a bunch of extra flags we don't need for Trick.
Now when we look for python with configure, it will search for python in this order:
python${PYTHON_VERSION}
python
python3
For python-config, it will search in this order:
python<major_version.minor_version>-config
python<major_version>-config
python${PYTHON_VERSION}-config
python-config
python3-config
Instead of python-config --ldflags, we are using python-config --libs 
This only gets the flags we need.
For python >= 3.8 we use
python-config --libs …
=> Ubuntu 20.04, Python 3.8, and improved python configuration in configure.ac

trick_sims/SIM_wheelbot/models/Control/src/PIDController.cpp, trick_sims/SIM_wheelbot/models/Control/src/differentialDriveController.cpp
Changes suggested by Scott Fennell:
1. Initialize output_limited to false
2. Be consistent in the utilization of true/false or 1/0.
3. Initialize PIDControllers without calling class.
4. Use if and else if while comparing output bounds.
Changes made:
1. Initialize output_limited to false
2. Be consistent in the utilization of true/false or 1/0.
3. Initialize PIDControllers without calling class.
4. Chose to omit since not a performance bug.
=> Implement PIDController to Wheelbot

libexec/trick/pm/gte.pm
A Ubuntu 18.04+ user is getting a bad TRICK_HOST_CPU with gte due to a change in gcc 7.x.  The gcc -dumpversion meaning has changed.  For gcc 7+, you want to use gcc -dumpfullversion.  gcc 4.x does not have the -dumpfullversion option.  There is trick to make it work.
The trick is to use:
gcc -dumpfullversion -dumpversion (in that order!)
instead of
gcc -dumpversion
inside of <trickhome>/libexec/trick/pm/gte.pm.
If you do that, the version will be correct for gcc 4.x and gcc 7.x+.
That might not be the solution you want, but it is simple.  Another way would be to do a system call to see if gcc has the -dumpfullversion option and use it if it exists, but that is more code invasive.
=> Fix TRICK_HOST_CPU gcc version for Ubuntu 18.04+ (#1024)

trick_source/codegen/Interface_Code_Gen/makefile
filter -llibxml2.tbd from llvm-config --system-libs as temporay workaround for missing library, until this is fixed by llvm
=> #1038 llvm-config --system-libs on macOS is providing a bad ldflag

docs/documentation/install_guide/Install-Guide.md
Step 5 in the installation guide “Install cask to get java and xquartz” results in the following error: “Error: Cask 'java' is unavailable: No Cask with this name exists. Did you mean one of these?”, then giving some other possible downloads. It seems that Java cannot be installed using home-brew in this way. The way around this I used was to install Java from Oracle’s website (https://www.java.com/en/download/) and the JDK from here (https://www.oracle.com/java/technologies/javase-jdk15-downloads.html), then install the other packages on their own. This has been tested to be working on macOS Catalina.
=> Trick installation on MacOS documentation update

trick_source/codegen/Interface_Code_Gen/FieldDescription.cpp, trick_source/codegen/Interface_Code_Gen/FieldDescription.hh, trick_source/codegen/Interface_Code_Gen/FieldVisitor.cpp, trick_source/codegen/Interface_Code_Gen/PrintFileContents10.cpp, trick_source/codegen/Interface_Code_Gen/PrintFileContentsBase.cpp, trick_source/sim_services/MemoryManager/MemoryManager_ref_name.cpp
This PR adds support for references over the variable server and data recording, but not checkpointing.
Fixes #1092
=> Add reference support to memory manager

share/trick/sim_objects/default_trick_sys.sm
If you use the -Wshadow flag, there are few compiler warnings
for shadowing. You can recreate with the Ball L1 sim:
% vi S_overrides.mk
TRICK_CFLAGS += -Wshadow -I../models
TRICK_CXXFLAGS += -Wshadow -I../models
% trick-CP
...
In file included from build/S_source.cpp:3:0:
build/../S_source.hh: In member function ‘void EventManagerSimObject::create_thread_process_event()’:
build/../S_source.hh:425:23: warning: declaration of ‘name’ shadows a member of 'this' [-Wshadow]
char* name = strdup(oss.str().c_str()) ;
To fix the S_source* generated code, it is just a
matter of changing default_trick_sys.sm.
=> Fix compiler shadow warning for issue #1141

trick_source/trick_utils/units/test/UnitTestSuite.cpp
This commit fixes the (misspelled) name of a unit test.
=> Fix unit test name (RankineToCelsius)

libexec/trick/make_makefile_swig, share/trick/makefiles/trickify.mk, trick_source/codegen/Interface_Code_Gen/PrintAttributes.cpp
`ICG` and `make_makefile_swig` create `py_link_list` and `io_link_list` files listing the files to be linked during sim builds. Trickified projects require slightly altered lists.
=> Create link_list files for Trickification

libexec/trick/pm/launch_java.pm
closes #613 
Still getting a message that macOS does not support EAWT (a different exception) but no stack trace
=> add workaround for legacy code (bsaf)  on modern mac with java 17

docs/tutorial/ATutMonteCarlo.md
Hi, I found a typo in the documentation for the Monte Carlo Simulation in the Tutorial Section.
Here is the [link](https://nasa.github.io/trick/tutorial/ATutMonteCarlo#simulation-definition-1).
=> fixing doc typo for tutorial

trick_source/sim_services/Executive/Executive_signal_handler.cpp
=> Stop attaching a debugger on segfault on Mac

trick_source/sim_services/VariableServer/vs_format_ascii.cpp
Using the same buffer for the destination and as a parameter for sprintf is undefined behavior. We were doing this previously all over vs_format_ascii without issue:
```
sprintf(value, "%s {%s}", value, ref->units);
```
However, snprintf seems to handle that undefined behavior differently, and was overwriting anything else in value in this specific place. 
This pull request is meant to be a hotfix, but this whole section of the variable server really needs to be refactored.
Link #1409
=> Patch for #1409

.github/workflows/alt_linux_distros.yml, .github/workflows/report_alt_linux_distros.yml, .github/workflows/test_32.yml, share/trick/trickops/tests/trick_sims.yml, share/trick/trickops/tests/ut_TrickWorkflow.py, test/SIM_test_varserv/S_overrides.mk
- Update S_overrides.mk for SIM_test_varserv so it links correctly in 32 bit (why did only that one have a problem? the world will never know)
- Stop testing Debian Bookworm on python2.7 since support was removed
- Fix some TrickOps unit tests
=> Fix various issues in scheduled CI jobs

docs/documentation/running_a_simulation/Input-File.md, include/trick/IPPythonEvent.hh, share/trick/swig/shortcuts.py, test/SIM_events/RUN_test/unit_test_error1.py, test/SIM_events/RUN_test/unit_test_error2.py, test/SIM_events/RUN_test/unit_test_error3.py, test_sims.yml, trick_source/sim_services/InputProcessor/IPPython.cpp, trick_source/sim_services/InputProcessor/IPPythonEvent.cpp
closes #1433 
closes #693 
Adds a command to terminate the sim on event processing failure:
```python
trick.terminate_on_event_parse_error(<True|False>)
```
Tests and documentation update included.
=> Add option to terminate sim on python event error

trick_sims/SIM_aircraft/RUN_test/input.py, trick_sims/SIM_aircraft/models/graphics/Makefile, trick_sims/SIM_aircraft/models/graphics/pom.xml, trick_sims/SIM_aircraft/models/graphics/src/main/java/trick/aircraftDisplay/AircraftDisplay.java
Getting SIM_aircraft in a good state for Trick intern. Maven is easier and more reliable than building .jar directly from Makefile.
=> Use Maven to build AircraftDisplay.jar instead of directly from Makefile

test_sims.yml, trick_source/sim_services/CheckPointAgent/ClassicCheckPointerAgent.cpp
Closes #1399 
It appears that the checkpointing bug we were seeing in #1399 was due to the checkpoint logic reading uninitialized memory  that happens when an empty array of strings is creating and deciding to write it as a string instead of an array. This patch checks to make sure that when we write as a quoted string, we are in the correct dimension.
=> 1399 patch

libexec/trick/pm/parse_s_define.pm, test/SIM_job_class_order/S_define
Broke some existing sims that reorder the integ_loop with #1465 . This fixes that.
=> Allow integ_loop to be reordered

trick_source/sim_services/Executive/Executive_fpe_handler.cpp
And remove buggy Mac implementation
closes #1385
=> Fix path for debugger commands in Executive_fpe_handler.cpp

Makefile, docs/documentation/building_a_simulation/Making-the-Simulation.md, trick_source/codegen/Interface_Code_Gen/main.cpp
Add an option to ICG to control the C++ standard it parses against. Currently, the default is whatever the newest version supported by LLVM is. 
```
TRICK_CXXFLAGS += -std=c++11
```
Valid options are c++11, c++14, c++17, c++20. 
Also adds a convenience target to the root Makefile for the ICG executable.
=> Add option to specify a C++ standard to ICG for parsing

.github/workflows/test_32.yml, .github/workflows/test_32_oracle.yml, Makefile, test_overrides.mk, test_sims32.yml, trickops.py
The 32 bit pipeline frequently has issues that are only related to the test suite itself and its dependencies, which makes it require more maintenance than value provided. Change this pipeline to only build trick and a handful of example sims.
=> Change 32 bit pipeline to only build part of the test suite

docs/howto_guides/Checkpointing-Best-Practices.md
"Other Resources You Might Find Useful" sections have the ssh version of the repo url and not the https version.
_Originally posted by @sharmeye in https://github.com/nasa/trick/pull/1549#pullrequestreview-1577767115_
=> Fix Other Resources links in Checkpointing-Best-Practices.md

trick_source/sim_services/Sie/Sie.cpp
When creating the sie file there is a marker string that Trick searches for where it writes the run time allocated memory.  The loop that was searching for the string was iterating one character at a time and reading from file each time.  This was slow.  Changed the loop to read 1Mb into memory at a time and search for the string.  Handled the case where the marker string could straddle the 1Mb boundary by copying a small portion of the previous part of the file for the next search.  For my one test point sie file generation dropped from 90+ seconds to 3.5 seconds.
=> Possible speedup for requesting sie file #1555

.github/workflows/test_linux.yml
In order to avoid using okay-release-1-6.el7.noarch.rpm that is causing an error for some reason.
=> Changed to install googletest 1.8.0 for centos 7 instead of using 1.6.0

include/trick/swig/swig_int_templates.hh
Updated swig_int_templates.hh to use PyUnicode_GET_LENGTH if available otherwise use PyUnicode_GET_SIZE for Python 3 as PyUnicode_GET_LENGTH is new in Python 3.3 and PyUnicode_GET_SIZE is deprecated in Python 3.3 and removed in Python 3.12.
=> Use PyUnicode_GET_LENGTH when possible otherwise use PyUnicode_GET_SIZE for Python 3

include/trick/Event.hh
Removed inheritance from binary_function for c++11 or later and kept the inheritance for standards earlier than c++11
=> Changed not to inherit from binary_function for c++11 or above.

libexec/trick/convert_swig
convert_swig did not previously understand the "enum class".  Made a regular expression to catch it.  We don't have to do anything special with it for convert_swig, the matched contents are written to the output file as is.
=> Trick Fails to Compile Sims with enum classes #1611

include/trick/mc_variable.hh, include/trick/mc_variable_file.hh, include/trick/mc_variable_random.hh, include/trick/mc_variable_random_normal.hh, include/trick/mc_variable_random_string.hh, include/trick/mc_variable_random_uniform.hh, test/SIM_mc_generation/RUN_WARN_no_string_values/input.py, test/SIM_mc_generation/verif_data/MONTE_RUN_nominal/MonteCarlo_Meta_data_output, test/SIM_mc_generation/verif_data/MonteCarlo_Meta_data_output, test_sims.yml, trick_source/sim_services/MonteCarloGeneration/mc_master.cc, trick_source/sim_services/MonteCarloGeneration/mc_variable.cc, trick_source/sim_services/MonteCarloGeneration/mc_variable_file.cc, trick_source/sim_services/MonteCarloGeneration/mc_variable_random_normal.cc, trick_source/sim_services/MonteCarloGeneration/mc_variable_random_string.cc, trick_source/sim_services/MonteCarloGeneration/mc_variable_random_uniform.cc
Originally requested by a user in discussions in Ramtares GitLab merge request 6053, this MR implements a better and more robust solution than the originally proposed approach. 
* Add `type`, `dispersion`, `min_value`, `max_value` and other relevant internal members of `MonteCarloVariable*` classes to the output of `MonteCarlo_Meta_data_output`
* Fix an edge case in `MonteCarloVariableRandomStringSet::generate_assignment()` if no string values are added to the instance. Add a verif sim run to cover this case.
=> MonteCarloGenerate: Add more metadata to MonteCarlo_Meta_data_output

docs/documentation/building_a_simulation/Environment-Variables.md
I also shifted the TRICK_ICG_EXCLUDE section to be contiguous with the TRICK_EXCLUDE. This way it should be a bit easier to find the exclude tags.
=> Update Environment Variables to cover TRICK_SWIG_EXCLUDE

trick_source/sim_services/Executive/Threads.cpp
Dump cycle time for all types instead of just PROCESS_TYPE_AMF_CHILD.
=> S_job_execution enhancement #1637 

include/trick/RealtimeSync.hh, trick_source/java/src/main/java/trick/simcontrol/SimControlApplication.java, trick_source/sim_services/RealtimeSync/RealtimeSync.cpp
Added calculations in the realtime sync monitor job to calculate the average sim/realtime ratio for the past 100 frames.  This is saved to a new variable, actual_run_ratio.  Changed the sim control panel to display the actual_run_ratio value.
=> Repurpose the "Sim/Real Time" field on the sim control panel #1626

include/trick/io_alloc.h, trick_source/sim_services/MemoryManager/MemoryManager.cpp, trick_source/sim_services/MemoryManager/MemoryManager_declare_var.cpp, trick_source/sim_services/MemoryManager/MemoryManager_delete_var.cpp, trick_source/sim_services/MemoryManager/test/MM_delete_var.hh, trick_source/sim_services/MemoryManager/test/MM_delete_var_unittest.cc, trick_source/sim_services/MemoryManager/test/Makefile
This is a re-do of PR 1539 associated with 1529.
=> Fix the alloc_type of allocations performed by declare_var. #1529

.github/workflows/test_macos.yml
As SWIG 4.2 generates setter wrapper for C++ private constructor or operator.
=> Update MacOS workflow to use SWIG 4.1.1 instead of the newest SWIG 4.2

share/trick/trickops/TrickWorkflow.py
This clears the "ValueError: ...  disabled for FIPS" exception for systems with FIPS mechanisms enabled. This is safe because hashlib is only used to compare baseline data to test data in trickops, it's not used for any security mechanisms.
FYI @hchen99 @jmpenn @sharmeye 
Closes #1661
=> TrickOps: Use usedforsecurity=False when calling hashlib.md5 for compare mechanism

include/trick/IPPython.hh, trick_source/sim_services/InputProcessor/IPPython.cpp
Implemented use of the python GIL API to replace the less portable mutex solution.
=> python3 GIL locking solution

include/trick/VariableServer.hh, include/trick/VariableServerListenThread.hh, trick_source/sim_services/Clock/test/Makefile, trick_source/sim_services/CommandLineArguments/test/Makefile, trick_source/sim_services/Executive/Executive_shutdown.cpp, trick_source/sim_services/Executive/test/Makefile, trick_source/sim_services/Integrator/test/Makefile, trick_source/sim_services/MemoryManager/test/Makefile, trick_source/sim_services/ScheduledJobQueue/test/Makefile, trick_source/sim_services/Timer/test/Makefile, trick_source/sim_services/VariableServer/VariableServer.cpp, trick_source/sim_services/VariableServer/VariableServerListenThread.cpp
Issue #1656 describes a deadlock condition that can occur at shutdown.
Many thanks to Cameron Bracco (cameronbracco) for an excellent writeup!
Whereas a fix was proposed, we'd like to try different approach that does rely on timers.
=> Proposed fix for deadlock on shutdown

.github/workflows/trickops.yml, share/trick/trickops/TrickWorkflow.py, share/trick/trickops/tests/trick_sims.yml
trick_sims.yml was "accidentally changed" to remove unstable sims in Sept 2023, breaking the TrickOps unit tests. This reverts that change.
=> Revert changes to trickops test yml file from Sept 2023 to fix trickops unit tests

docs/howto_guides/Realtime-Best-Practices.md
Remove a duplicate _frame from a plain text version of a filename
=> Fix typo in Realtime Best Practices

.github/workflows/test_macos.yml
Updated the MacOS CI workflow so that bash won't exit with brew upgrade exits with non-zero exit code.
=> Updated the MacOS CI workflow so that bash won't exit with brew upgrade exits with non-zero exit code.

trick_source/sim_services/JITInputFile/JITInputFile.cpp
Corrected .d file path for the clean target in Makefile.input file.
Before:
.d file path: RUN_xxx/RUN_xxx/jitlib/input.d
After:
.d file path: RUN_xxx/jitlib/input.d
=> Corrected .d file path for the clean target in Makefile.input file.

.github/workflows/test_linux.yml
Configured CentOS 7 to run with node 16.
=> CentOS 7 CI Failures - Run CentOS CI with Node 16 instead of 20

trick_source/sim_services/JITInputFile/JITInputFile.cpp
So that users can use TRICK_LDFLAGS for linking shared library if necessary. 
For instance, if a user has `TRICK_CXXFLAGS += -fprofile-arcs -ftest-coverage -I./models` in S_overrides.mk to compile a sim with code coverage flags, they can include `TRICK_LDFLAGS += --coverage` or `TRICK_LDFLAGS += -fprofile-arcs -ftest-coverage` in S_overrides.mk for the generated shared library to be loaded correctly.
=> Added TRICK_LDFLAGS to the rule for linking shared library for jit input.

trick_source/sim_services/ScheduledJobQueue/ScheduledJobQueue.cpp
=> Speed up Trick::ScheduledJobQueue::push

docs/documentation/install_guide/Install-Guide.md
Using `default-jdk` instead of a specific JDK version so that if there is JRE installed by default, it'll be consistent with the JDK. 
Ubuntu 24 has JRE (version 21) headless set up by default in `/usr/bin`.
Installing openjdk-11-jdk in ubuntu24 does set up openjdk-11-jre however in `/usr/lib/jvm/java-11-openjdk-amd64/bin` instead of `/usr/bin`. openjdk-11-jre doesn't replace the JRE headless in `/usr/bin` probably because the default one is a newer version. 
If using openjdk-11-jdk package in ubuntu24, the user needs to set their environment path to use openjdk-11-jre (`java` command for running Java GUIs) first otherwise, they'd get an error by running Java GUIs using headless JRE from `/urs/bin` by default.
Using `default-jdk` works for ubuntu 18, 20, 22, and 24. Using openjdk-11-jdk …
=> Updated to use default-jdk package instead of openjdk-11-jdk for ubuntu.

.github/workflows/trickops.yml
trickops.yml needs to be updated to use a newer Ubuntu than Ubuntu 20 since the latest koviz removed deprecated calls from an older Qt on Ubuntu 20. The koviz update is necessary to keep up with Qt changes.
=> Updated trickops.yml to use a newer Ubuntu

include/trick/ExternalApplication.hh, trick_source/sim_services/ExternalApplications/ExternalApplication.cpp, trick_source/sim_services/VariableServer/VariableServerListenThread.cpp
1. When an external app such as the sim control panel is configured as following in the input file, the corresponding destructor gets called at the shutdown. In turn, the MM will try to clean the memory for the vars related to the external app even those vars were already taken care of due to the shutdown. Thus there was a warning message. 
`simControlPanel = trick.SimControlPanel()`
`trick.add_external_application(simControlPanel)`
However, if having `trick.sim_control_panel_set_enabled(True)` in the input file, there was no warning message.
Deleted the unnecessary command c str pointer, thus removed the need to free its memory allocation as before. 
2. Made sure that the multicast group is not initialized before calling a function to initialize it in VariableServerListenThread.cpp. …
=> Fixed one warning message at shutdown after checkpoint load and kept the current multicast group after checkpoint load.

trick_source/sim_services/ScheduledJobQueue/ScheduledJobQueue.cpp
The Job Queue push update did not properly track the queue's current index. I re-implemented that feature.
=> Preserved job queue currant index after pushing a job.

trick_source/codegen/Interface_Code_Gen/PrintAttributes.cpp, trick_source/codegen/Interface_Code_Gen/Utilities.cpp, trick_source/codegen/Interface_Code_Gen/Utilities.hh, trick_source/codegen/Interface_Code_Gen/main.cpp
Since the corresponding `getName` function of FileEntry is deprecated for clang18+, using FileEntryRef `getName` instead.
=> Updated to use FileEntryRef to get name instead of FileEntry for clang18+.

libexec/trick/convert_swig
And moved the call to right after struct declaration instead of at the end of the swig interface file. 
See PR#1718 for the original fix.
=> Added _swig_setattr_nondynamic_instance_variable function call back for struct

.github/workflows/report_linux_py2.yml, .github/workflows/test_linux.yml, .github/workflows/test_macos.yml, .github/workflows/trickops.yml
Updated to Github actions v4 as Github actions v3 will be closing down by 1/30/25.
=> Updated to Github actions v4

.github/workflows/alt_linux_distros.yml, .github/workflows/code_coverage.yml, .github/workflows/python_tests_linux.yml, .github/workflows/python_tests_macos.yml, .github/workflows/report_alt_linux_distros.yml, .github/workflows/report_linux.yml, .github/workflows/report_linux_py2.yml, .github/workflows/report_macos.yml, .github/workflows/test_32_oracle.yml, .github/workflows/test_linux.yml, .github/workflows/test_linux_py2.yml, .github/workflows/test_macos.yml, .github/workflows/trickops.yml
The initial update for issue#1821 only changed lines auto generated by GitHub and those lines are only for artifacts. This additional update is for updating actions@checkout at the v4 branch as well.
=> 1821 action required GitHub actions v4 update for actions@checkout

.github/workflows/report_alt_linux_distros.yml, .github/workflows/report_linux.yml, .github/workflows/report_linux_py2.yml, .github/workflows/report_macos.yml
Testing the workaround for GitHub test report v1 to work with action v4 and if not working, will have to change the GitHub action version to v3 while leaving GitHub artifact version as v4 as required.
=> Added the workaround for GitHub test report v1 to work with action v4.

.github/workflows/report_alt_linux_distros.yml, .github/workflows/report_linux.yml, .github/workflows/report_linux_py2.yml, .github/workflows/report_macos.yml
This reverts commit 02267fb391a424539d6848c55eb3438da42fab14.
=> Revert "Added the workaround for GitHub test report v1 to work with action v4."

trick_source/java/src/main/java/trick/jobperf/JobPerf.java, trick_source/java/src/main/java/trick/jobperf/JobSpecificationMap.java
1) Default --report to false when jperf runs in GUI mode,  and true when run in batch mode.
Rationale: reporting is the only thing you can do in batch, but in GUI mode you can see jobs stats in a GUI window any time you like.
2) Clean up left over debug messages.
=> Default to --report when run in batch. Also remove debug message output.

trick_source/sim_services/Message/MessagePublisher.cpp, trick_source/sim_services/Message/message_publish_standalone.cpp, trick_source/trick_swig/swig_double.i, trick_source/trick_swig/swig_int.i
Updated to use the format method instead of f-strings for Python version compatibility and %lu for tv_usec to enhance portability.
=> Updated to use format method for string in .i file and %lu for tv_usec

.github/workflows/test_macos.yml
Pin googletest after the initial install to prevent it from being upgraded later. The initial installed version is v1.16 and upgrade would change it to v1.17 which causing error if not C++17 for certain gtest header files.
=> Pin googletest after install to prevent it from being upgraded later.

.github/workflows/test_macos.yml
Updated to install googltest 1.16.0 specifically as 1.17.0 needs C++17.
=> Updated to install googltest 1.16.0 specifically as 1.17.0 needs C++17.

trick_source/sim_services/Executive/Executive_fpe_handler.cpp, trick_source/sim_services/Executive/Executive_init_signal_handlers.cpp, trick_source/sim_services/Executive/fpe_handler.cpp, trick_source/sim_services/Executive/test/Executive_test.cpp
FPE signal handling has changed since the last time this code was touched, pre-2015.  Mac FPE signal handling works similar to linux now.  Was able to remove a lot of #if __APPLE__ sections of code. There is an Arm specific call on Apples to enable FPE, fesetenv. This is like linux specific feenableexcept.  I do not know what Macs on intel chips use, so I left that out, FPEs will still be broken on that platform combination.
=> FPEs don't work on Macs #1914

trick_source/sim_services/mains/master.cpp
Updated to call command_line_args_process_sim_args before memory_init() in master.cpp so that user command line args to S_main_*** can be used in memory_init().
=> Updated to call command_line_args_process_sim_args before memory_init() in master.cpp

trick_source/sim_services/InputProcessor/IPPython.cpp
Need to clear the python trace function after the input file has been read completely.
=> Add capability to save input file used during run #1928

trick_source/sim_services/InputProcessor/IPPython.cpp
Added an if check before in the python code run before the input file and test if the VIRTUAL_ENV environment variable is set.  If it is, add the path ${VIRTUAL_ENV}/python_<version>/site-packages to sys.path list.
=> Add python virtual environment path to Input processor search path #1944

trick_source/sim_services/RealtimeSync/RealtimeSync.cpp
Protect against a repeated sample values which can result in a divide by zero. Use an if-check instead of modulo operator (possibly faster)?
fixes #1957
=> Resolves potential-for-fpe-in-run_ratio-sample-calcs 
